// Renders the Compose project the way an operator install does: a private state
// generated by configure.mjs from sentinel provider values, then the ownership
// wrapper's `compose --profile '*' config`. Nothing is built, pulled or started.
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { configure } from '../scripts/configure.mjs';

const root = new URL('..', import.meta.url).pathname;
let rendered;

export function composeAvailable() {
  return spawnSync('docker', ['compose', 'version'], { encoding: 'utf8' }).status === 0;
}

export function renderedCompose() {
  if (rendered) return rendered;
  const scratch = mkdtempSync(join(tmpdir(), 'warehouse-compose-render-'));
  try {
    const stateDir = join(scratch, 'state');
    const providerEnv = join(scratch, 'provider.env');
    writeFileSync(providerEnv, 'SMS_PROVIDER=msg91\nMSG91_AUTH_KEY=isolated-no-delivery-key\nMSG91_TEMPLATE_ID=000000000000000000000001\nMSG91_PE_ID=0000000000000000001\nMSG91_SENDER_ID=CITEST\n', { mode: 0o600 });
    configure(root, { stateDir, apiUrl: 'https://compose-render.example.test', company: 'Compose Render', providerEnv });
    const result = spawnSync('bash', [join(root, 'scripts/compose.sh'), '--profile', '*', 'config', '--format', 'json'], {
      encoding: 'utf8', maxBuffer: 16 * 1024 * 1024, env: { ...process.env, WAREHOUSE_STATE_DIR: stateDir },
    });
    if (result.status !== 0) throw new Error(`compose config failed: ${result.stderr}`);
    rendered = JSON.parse(result.stdout);
    return rendered;
  } finally { rmSync(scratch, { recursive: true, force: true }); }
}
