import{PassThrough}from'node:stream';import{setTimeout as wait}from'node:timers/promises';import{bufferConcurrencyRequest}from'./fixture-dispatch-concurrency-delay.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import{dispatchConcurrencyDelayMilliseconds as delay}from'./fixture-dispatch-concurrency-delay.mjs';
const config={scope:'isolated-fictional-native-dispatch-concurrency',milliseconds:5000,record:'FXQ994',lotId:'11111111-1111-4111-8111-111111111111'};
const req={method:'POST',headers:{host:'backend-core.example.test',authorization:'mock-private-access'}};
const target=new URL('http://127.0.0.1:18080/rest/v1/rpc/create_dispatch_with_stock_check');
const body=()=>({p_dispatch_data:{disp_no:'FXQ994',customer_id:'a823809c-bdb6-11f1-b1be-47a66d90b06d',supervisor_id:'947136fa-997b-4a83-819d-1b8bd3ecba68',source_order_id:null},p_dispatch_items:[{gr_trl_id:config.lotId,disp_qty:2}],p_generate_invoice:true,p_retry_count:0,p_idempotency_key:'mock-concurrency-key'});
test('only the exact declared fictional native dispatch can match, and default is disabled',()=>{assert.equal(delay(req,target,body()),0);assert.equal(delay(req,target,body(),config),5000);});
test('other records, accounts, lots, quantities, routes, credentials and excessive waits cannot match',()=>{for(const mutate of[b=>b.p_dispatch_data.disp_no='FXQ995',b=>b.p_dispatch_data.customer_id='other',b=>b.p_dispatch_data.source_order_id='other',b=>b.p_dispatch_items[0].gr_trl_id='other',b=>b.p_dispatch_items[0].disp_qty=3,b=>b.p_dispatch_items.push({...b.p_dispatch_items[0]}),b=>b.p_retry_count=1,b=>delete b.p_idempotency_key]){const b=body();mutate(b);assert.equal(delay(req,target,b,config),0);}assert.equal(delay({...req,headers:{host:'backend-switch.example.test'}},target,body(),config),0);assert.equal(delay(req,new URL(target+'?token=mock'),body(),config),0);assert.equal(delay(req,new URL('http://127.0.0.1:18080/rest/v1/rpc/get_orders_list'),body(),config),0);assert.throws(()=>delay(req,target,body(),{...config,milliseconds:5001}));});

test('eligible request is forwarded once after the bound and metadata contains no payload',async()=>{const r=new PassThrough();Object.assign(r,req);let forwarded;const events=[];const started=Date.now();bufferConcurrencyRequest(r,target,{...config,milliseconds:500},{forward:b=>{assert.equal(forwarded,undefined);forwarded=b;},fail:()=>assert.fail('unexpected failure'),observe:e=>events.push(e)});const raw=Buffer.from(JSON.stringify(body()));r.end(raw);await wait(30);assert.equal(forwarded,undefined);await wait(550);assert.deepEqual(forwarded,raw);assert.ok(Date.now()-started>=500);assert.deepEqual(events.map(e=>e.event),['dispatch-request-delay-start','dispatch-request-delay-release']);assert.ok(!JSON.stringify(events).includes('mock-concurrency-key'));});
test('cancellation prevents upstream execution and oversized buffering refuses',async()=>{const r=new PassThrough();Object.assign(r,req);let count=0;const cancel=bufferConcurrencyRequest(r,target,{...config,milliseconds:500},{forward:()=>count++,fail:()=>assert.fail('unexpected failure')});r.end(JSON.stringify(body()));await wait(20);cancel();await wait(550);assert.equal(count,0);const big=new PassThrough();Object.assign(big,req);let failure;bufferConcurrencyRequest(big,target,config,{forward:()=>assert.fail('oversize forwarded'),fail:(event,status)=>failure={event,status}});big.end(Buffer.alloc(65537));await wait(10);assert.deepEqual(failure,{event:'concurrency-body-bound',status:413});});
test('nonmatching or malformed requests are forwarded unchanged without waiting',async()=>{for(const raw of[Buffer.from('{malformed'),Buffer.from(JSON.stringify({...body(),p_retry_count:1}))]){const r=new PassThrough();Object.assign(r,req);let forwarded;bufferConcurrencyRequest(r,target,config,{forward:b=>forwarded=b,fail:()=>assert.fail('unexpected failure')});r.end(raw);await wait(20);assert.deepEqual(forwarded,raw);}});
